name: "Exercicio 01 Data atual"

on:
  push:
  
jobs:
  print_date_ubuntu:
    name: Print Date Ubunto!
    runs-on: ubunto-latest
  
    steps:
      - name: Print Date Ubunto!
        run: date
  
  print_date_windows:
    name: Print Date Windows!
    runs-on: windows-latest
    
    steps:
      - name: Print Date Windows!
        run: date
  
  print_date_macos:
    name: Print Date Macos!
    runs-on: macos-latest
    
    steps:
      - name: Print Date Macos!
        run: date
  
  print_date_ubunto_final:
    name: Print Date Ubunto Final!
    runs-on: ubunto-latest
       
  needs:
      - print_date_ubuntu
      - print_date_windows
      - print_date_macos

    steps:
      - name: Print Date Ubunto Final!
        run: date
