name: "Data atual"

on:
  push:
  
jobs:
  print_date_ubuntu_01:
    name: date
    runs-on: ubunto-latest
  
  print_date_windows_02:
    name: date
    runs-on: windows-latest
  
  print_date_macos_03:
    name: date
    runs-on: macos-latest
  
  print_date_ubuntu_04:
    name: date
    runs-on: ubunto-latest
    needs: 
      - print_date_ubuntu_01
      - print_date_windows_02
      - print_date_ubuntu_03
