name: "Exercicio 01 - Data atual"

on:
  push:
  
jobs:
  print_date_ubuntu_01:
    name: Print Date Ubunto!
    runs-on: ubunto-latest
  
    steps:
      - name: Print Date Ubunto
        run: date
  
  print_date_windows_02:
    name: date
    runs-on: windows-latest
    
    steps:
      - name: Print Date Windows!
        run: date
  
  print_date_macos_03:
    name: date
    runs-on: macos-latest
    
    steps:
      - name: Print Date Macos!
        run: date
  
  print_date_ubuntu_04:
    name: date
    runs-on: ubunto-latest
       
    needs: 
      - print_date_ubuntu_01
      - print_date_windows_02
      - print_date_ubuntu_03

steps:
      - name: Print Date Ubunto
        run: date
